services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction_api
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:6969"
   
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=YOUR_ELASTIC_PASSWORD
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elk-network
    restart: unless-stopped
 
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjpKNHUtNWk0YlN6ZTFEcUIzVVVDZFlB
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk-network
    restart: unless-stopped
    volumes:
      - kibana_data:/usr/share/kibana/data

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: P@ssw0rd
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  es_data:
    driver: local
  kibana_data:
    driver: local
  rabbitmq_data:
    driver: local
 
networks:
  elk-network:
    driver: bridge
